openapi: "3.0.0"
info:
  title: Health Recorder OpenAPI
  description: "API description in Markdown. swagger doc: https://swagger.io/docs/specification/basic-structure/"
  version: 1.0.0
servers:
  - url: http://api.example.com
paths:
  /exercises:
    get:
      summary: Returns a list of exercises.
      description:
      parameters:
        - in: query
          name: offset
          description: page offset
          schema:
            type: integer
            format: int32
        - in: query
          name: limit
          description: page limit
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/definitions/ExerciseRecordList"
    post:
      summary: create exercises.
      requestBody:
       description: ""
       required: true
       content:
         application/json:
           schema:
             $ref: "#/definitions/ExerciseRecordRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
               $ref: '#/definitions/ExerciseRecordList'
  /exercises/{id}:
    get:
      summary: get exercises.
      parameters:
        - in: path
          name: id
          required: true
          description: exercise id
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/ExerciseRecord'
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - in: path
          name: userId
          required: true
          type: integer
          minimum: 1
          description: Parameter description in Markdown.
      responses:
        200:
          description: OK
components:
  schemas:
    ExerciseRecordList:
      type: object
      properties:
        total:
          type: integer
          description: total count
        items:
          type: array
          items:
            $ref: '#/definitions/ExerciseRecord'
    ExerciseRecord:
      type: object
      properties:
        id:
          type: integer
          # todo: complete

